import type { GraphNode, Option } from '../../src/engine/types';

// TR3: sustainable location. A gate under GB7(1)(g)(iii); elsewhere outside settlements, a weight in the balance.
const applies = { any: [{ in: ['gb', ['yes', 'washed-over']] }, { eq: ['outside', true] }] } as const;
const nonGB = { eq: ['outside', true] } as const;
const gate = { eq: ['gb7cat', 'g'] } as const;
// The full location assessment runs whenever TR3 applies, except outside the Green Belt where TR3(1)(a) is not
// engaged (not a significant amount of movement): there the location is a weight, not a route question.
const assess = { all: [applies, { not: { all: [nonGB, { in: ['tr3Engaged', ['no', 'no-moderate']] }] } }] } as const;

const q = (id: string, title: string, prompt: string, options: Option[], help?: string[], type: 'single' | 'multi' = 'single'): GraphNode => ({
  id,
  kind: 'question',
  section: 'location',
  fact: id,
  when: assess,
  whyShown: 'The site is in the Green Belt or outside a settlement, so the location is tested against TR3.',
  title,
  prompt,
  input: { type, options },
  ...(help ? { help } : {}),
});

export const tr3: GraphNode[] = [
  {
    id: 'tr3Engaged',
    kind: 'judgement',
    section: 'location',
    fact: 'tr3Engaged',
    when: nonGB,
    whyShown: 'Outside a settlement, TR3(1)(a) applies only where the proposal would generate a significant amount of movement in its context.',
    title: 'TR3(1)(a): is a significant amount of movement generated?',
    prompt: 'Would the proposal generate "a significant amount of movement, in the context of the area within which [it] would be situated"?',
    quotes: ['TR3(1)(a)'],
    help: [
      'There is no fixed number — judge it against the size and pattern of the surrounding area, not in the abstract.',
      'A handful of homes has been significant in a small or sparsely built village: five homes were "a significant amount of movement in this context" (6010313 ¶13). A single dwelling among existing houses has not (one home was not significant at 6010973 ¶20).',
      'If it is not engaged, TR3(1)(a) is not a decisive matter, but reliance on the car is still weighed in the planning balance (P12). Inspectors have differed on how much: limited weight is common, but one home with TR3(1)(a) not engaged was given "moderate negative weight" for a poor walking route (6010422 ¶49), and another single home was held to conflict with TR3\'s "more general principles about sustainable patterns of movement" (6008773 ¶30–32). Car dependence has also been treated as a DP3(2)(d) conflict without clear justification, engaging DP3(3) (6007677 ¶27). If it is engaged, the location must offer a genuine choice of transport modes, tested in the next steps.',
      'One inspector read the proviso "unless the nature of the development would make this impractical" as covering a change of use of an existing building (6009619 ¶18). The proviso refers to the nature of the development; whether a conversion meets it is a judgement to state.',
      'This step is not asked in the Green Belt: GB7(1)(g)(iii) requires a sustainable-location finding whatever the scale of the scheme. One home failed there on the route alone, "notwithstanding the small scale of the proposal" (6010253 ¶18).',
    ],
    method: {
      question: 'In the context of this area, would the movement generated by the proposal be significant enough to engage TR3(1)(a)?',
      steps: [
        'Judge the movement against the size, density and pattern of the surrounding area, not against a fixed threshold.',
        'A few homes can be significant in a small or sparsely built village (6010313 ¶13); a single dwelling among existing houses may not be (6010973 ¶20).',
        'If not engaged, record the car-reliance point as a weight in the balance (limited, or moderate where the route is poor) and move on. If engaged, assess the location in the following steps.',
      ],
      pointers: [
        { option: 'yes', factors: ['A group of homes in a small village or a sparsely built rural area', 'The trips generated are noticeable against a lightly trafficked local network'] },
        { option: 'no', factors: ['A single dwelling among existing houses on a built-up frontage (6010973 ¶20)', 'The added movement is negligible against the existing pattern'] },
      ],
      closeCall: 'The threshold is low and contextual. Where there is real doubt, treat TR3(1)(a) as engaged and assess the location; the alternative is to under-weigh car reliance.',
    },
    input: {
      type: 'single',
      options: [
        { value: 'yes', label: 'Yes: a significant amount of movement in this context' },
        { value: 'no', label: 'No: not a significant amount of movement in this context' },
        { value: 'no-moderate', label: 'No, but the car reliance still carries moderate weight here (for example a poor walking route)' },
      ],
    },
    effects: [
      { when: { eq: ['tr3Engaged', 'yes'] }, finding: { kind: 'note', policy: 'TR3(1)(a)', text: 'TR3(1)(a) is engaged: the proposal would generate a significant amount of movement in this context, so the location must offer a genuine choice of transport modes.' } },
      { when: { eq: ['tr3Engaged', 'no'] }, finding: { kind: 'harm', weight: 'limited', policy: 'TR3(1)(a)', text: 'The proposal would not generate a significant amount of movement in this context, so TR3(1)(a) is not engaged; any reliance on the car carries limited weight.' } },
      {
        when: { eq: ['tr3Engaged', 'no-moderate'] },
        finding: { kind: 'harm', weight: 'moderate', policy: 'TR3(1)(a)', text: 'TR3(1)(a) is not engaged, as the proposal would not generate a significant amount of movement in this context, but its reliance on the car still carries moderate weight (as at 6010422 ¶49).' },
      },
    ],
    cases: { policies: ['TR3(1)(a)'], groupBy: 'finding' },
  },
  q('tr3Footway', 'Walking route: footway', 'On the everyday walking route from the site to shops, school and public transport, which of these describe the pedestrian provision? Select all that apply.', [
    { value: 'continuous', label: 'A continuous footway of adequate width for the whole route' },
    { value: 'narrow', label: 'Narrow for some or all of the route: too narrow for a wheelchair or pushchair to pass another person' },
    { value: 'oneSide', label: 'On the far side of the road only, so residents must cross to reach it' },
    { value: 'gaps', label: 'Gaps with no footway, where people walk in the carriageway or on the verge' },
    { value: 'surface', label: 'Broken or uneven surface, or obstructions such as poles or overgrown vegetation' },
    { value: 'notStepFree', label: 'Not step-free: full-height kerbs, no dropped kerbs or tactile paving at crossings or the destination' },
    { value: 'none', label: 'No pedestrian provision for most of the route' },
  ], [
    'Measure the route people would actually use, not a straight-line distance.',
    'Width matters: a lit, continuous but narrow footway beside a busy road failed at 6008688 (¶14).',
    'TR4 is framed around the design of the development, but it asks for priority to walking, wheeling and cycling "both within the scheme and with neighbouring areas" (TR4(1)(a)) and for measures that "meet the needs of disabled people, older people and children" (TR4(1)(c)(ii)). A route to services that a wheelchair or pushchair cannot use is not a genuine choice for them under TR3(1)(a).',
  ], 'multi'),
  q('tr3Lit', 'Walking route: lighting', 'Is the walking route lit?', [
    { value: 'lit', label: 'Lit throughout' },
    { value: 'partly', label: 'Partly lit' },
    { value: 'unlit', label: 'Unlit' },
  ]),
  q('tr3Speed', 'Walking route: traffic speed', 'What speed limits apply where people walk beside or in the road? Select any that appear along the route.', [
    { value: '20-30', label: '20 or 30 mph' },
    { value: '40', label: '40 mph' },
    { value: '50plus', label: '50 mph or more' },
  ], ['Where the footway is narrow or absent, the speed beside it matters as much as the limit; a measured 85th-percentile speed is better evidence than the posted limit.'], 'multi'),
  {
    id: 'tr3SpeedEvidence',
    kind: 'question',
    section: 'location',
    fact: 'tr3SpeedEvidence',
    when: assess,
    whyShown: 'Recorded traffic speeds on the walking route show how it is experienced on foot, alongside the posted limits.',
    title: 'Walking route: evidenced traffic speed',
    prompt:
      'What is the highest traffic speed evidenced anywhere on the walking route? Use the largest recorded figure at or below the 95th percentile (for example an 85th- or 95th-percentile speed from a speed survey or automatic traffic count).',
    help: [
      'Take the figure from the application\'s own survey where there is one, or from a highway authority, parish or community speed-watch survey. Note the source and date in your own record.',
      'The 85th-percentile speed is the usual design measure: highway authorities set visibility splays from it.',
      'Where recorded speeds exceed the limit beside a narrow or missing footway, that is evidence about how attractive the route is to walk, not only about highway safety.',
    ],
    input: { type: 'number', min: 5, max: 100, step: 0.1, unit: 'mph', skip: { value: 'none', label: 'No speed survey' } },
  },
  q('tr3Services', 'Everyday services', 'How far is the walk to everyday services (food shop, primary school, GP)?', [
    { value: 'under800', label: 'Within about 800 m' },
    { value: '800to2k', label: 'About 800 m to 2 km' },
    { value: 'over2k', label: 'More than 2 km, or not available locally' },
  ], ['Measure to the services, not to the edge of the settlement: distances of 0.72 km and 1.15 km to two town edges did not count, because "the distance to key services, facilities and public transport would be significantly further" (6006224 ¶13).']),
  q('tr3Bus', 'Bus service', 'What bus service is within reasonable walking distance?', [
    { value: 'frequent', label: 'Frequent: at least hourly through the day, including weekends' },
    { value: 'limited', label: 'Limited: a few journeys a day, or weekdays only' },
    { value: 'minimal', label: 'Minimal: one or two days a week, or demand-responsive without evidence it serves the site' },
    { value: 'none', label: 'None' },
  ], [
    'Inspectors want evidence of frequency, hours, destinations and reliability (6009966 ¶22). A twice-weekly bus did not help at 6006637 (¶15). With a timetable in evidence, six buses a day Monday to Saturday, with none in the evenings, on Sundays or bank holidays, was not frequent enough for day-to-day needs (6007668 ¶15, ¶19).',
    'At inquiry, a bus about every two hours, with no service at commuting times, was still "a genuine sustainable transport mode" for daytime trips such as grocery shopping, alongside term-time school buses; the inspector accepted that commuting by public transport would be challenging (6006497 ¶37–40).',
  ]),
  q('tr3Rail', 'Rail', 'Is there a railway station within reasonable walking distance?', [
    { value: 'wellConnected', label: 'A well-connected station (Annex B) within about 800 m' },
    { value: 'limited', label: 'A station within walking distance, but not well-connected, or reached on a poor route' },
    { value: 'none', label: 'No' },
  ]),
  q('tr3Tool', 'Connectivity Tool', 'What does the DfT Connectivity Tool score the site (overall, excluding driving)?', [
    { value: 'low', label: 'Low: under about 30' },
    { value: 'mid', label: 'Middle: about 30 to 50' },
    { value: 'high', label: 'High: over about 50' },
    {
      value: 'notRun',
      label: 'Not run',
      effects: [{ kind: 'note', policy: 'TR3(2)', text: 'Evidence gap: the Connectivity Tool has not been run, although TR3(2) says it "should be used alongside other relevant quantitative or qualitative evidence".' }],
    },
  ], [
    'TR3(2) says the tool "should be used alongside other relevant quantitative or qualitative evidence".',
    'The same score has gone both ways: 52 failed at 6011736 and passed at 6010471. The tool does not measure footway width or lighting.',
    'The score "is a relative measure not an absolute measure of connectivity" and "should always be interpreted comparatively" (6006497 ¶42, inquiry). There a 52 was read against the authority\'s own bands and against settlements where development is accepted (¶43–44). A high percentile within a rural class did not help where the route failed (6006224 ¶11, ¶13), and a bare score with a map carried little weight (6010253 ¶19).',
  ]),
  {
    id: 'tr3',
    kind: 'judgement',
    section: 'location',
    fact: 'tr3',
    when: assess,
    suggest: { fact: 'tr3Lean', extra: { balanced: 'Finely balanced — a genuine close call' } },
    notes: { fact: 'tr3Notes', label: 'Other material considerations (optional)', placeholder: 'e.g. a secured footway improvement, a school within the site, local speed-watch data, an on-demand bus with evidence…' },
    title: 'TR3: is this a sustainable location?',
    prompt:
      'Taking the route, the services and the transport together, would the location limit the need to travel, particularly by private car, and offer a genuine choice of transport modes for residents?',
    quotes: ['TR3(1)(a)', 'TR3(1)(e)', 'TR3(2)', 'GB7(1)(g)(iii)', 'TR4(1)(a)', 'TR4(1)(c)', 'TR4(1)(c)(ii)'],
    help: [
      'The walking route usually decides this limb, not the distance. Contested inspector failures have had one or more of: no footway or a broken one, no lighting, walking in the carriageway, 40–60 mph traffic, and thin or unevidenced public transport (6010313, 6009966, 6011736, 6007428, 6008528, 6012481, 6006637).',
      'Contested passes had a continuous footway for most of the route, or a short benign gap, plus an evidenced bus service (6010471, 6011103, 6009645, 6011301, 6005877).',
      'Walking in the carriageway on the everyday route is the most reliable failing fact. Lighting does not cure it, and a short distance does not excuse it (6007428 ¶15–16).',
      'Small schemes are not exempt: five homes were "a significant amount of movement in this context" (6010313 ¶13).',
      'A highway authority\'s "no objection" answers highway safety and network capacity (TR3(1)(c), TR6(4)). It does not answer whether the location limits the need to travel by car and offers a genuine choice of transport modes (TR3(1)(a), GB7(1)(g)(iii)). At 6007668 ¶19 the highway authority raised no objection, but the inspector still found "an unsustainable location".',
      'Counts, housing only: inspectors passed this limb 11 times and failed it 9; councils passed it 15 times and failed it twice. Appeals are mostly of refusals, so the two groups are not like for like.',
    ],
    method: {
      question: 'Would future residents, including those who cannot or do not drive, have a genuine choice of transport modes for everyday trips, or would they in practice depend on the car?',
      steps: [
        'In the Green Belt, GB7(1)(g)(iii) requires a sustainable-location finding whatever the scale of the scheme. Outside the Green Belt, whether TR3(1)(a) is engaged was decided in the previous step, and you reach this assessment only where it is. The provisional reading above is drawn from your route answers — treat it as a prompt, not the decision.',
        'Walk the actual route to the everyday destinations: shop, primary school, GP and bus stop. Record footway width and continuity, gaps where people walk in the carriageway, lighting, surface and crossings, and the traffic speed beside each section.',
        'Test the route for all users, including children, older people, and wheelchair and pushchair users (TR4(1)(c)(ii)), and after dark and in bad weather. An hourly bus 400 m away did not help where the first part of the walk was in the road: "would not be a realistic option for many future occupiers especially a parent with young children or those with mobility issues" (6010642 ¶13; similarly 6007158 ¶23 on "outside daylight hours and in inclement weather").',
        'Check the public transport on evidence: frequency, hours, destinations and reliability (6009966 ¶22). Then take the Connectivity Tool score alongside the route evidence, as TR3(2) says, not instead of it.',
        'Count planned improvements only where they are secured, including any provided by the development itself. Then ask whether the alternatives are realistic for everyday trips, not merely possible in principle (6008688 ¶17).',
      ],
      pointers: [
        {
          option: 'pass',
          factors: [
            'A continuous footway of adequate width for most of the route, or only a short, low-traffic gap',
            'Everyday services within a comfortable walk',
            'An evidenced bus service, usually at least hourly and running at the times people travel to work and school; a two-hourly daytime service has been accepted at inquiry for local trips, although commuting by public transport would be challenging (6006497 ¶38–40, ¶45)',
            'Secured improvements, such as a new footway link, that close the gaps: at inquiry, lit footpaths, new bridges over a trunk road, a toucan crossing and bus services within the site (6008238 ¶77–92)',
          ],
        },
        {
          option: 'fail',
          factors: [
            'Walking in the carriageway on the everyday route; lighting and a short distance do not cure it (6007428 ¶15–16)',
            'A narrow footway beside a busy road, even if lit and continuous (6008688 ¶14)',
            'An unlit lane with no footway at the national speed limit (6006950 ¶18)',
            'Bus service infrequent, or with no evidence of hours and destinations (6009966 ¶22)',
            'Reliance on existing residents\' car use or observed walking: use can reflect necessity, not choice, and does "not demonstrate that the route is universally perceived as safe" (6006637 ¶26; 6009718 ¶17)',
          ],
        },
      ],
      evidence: [
        'A walked route survey with photographs, footway widths and gaps',
        'Speed survey data (85th percentile) for sections without a footway',
        'Bus timetables showing frequency, first and last journeys, and destinations',
        'The Connectivity Tool output (TR3(2) says it "should be used"; record a gap if it has not been run)',
        'Details of any secured improvements and how they are secured',
      ],
      closeCall:
        'The test is a genuine choice for residents, not whether walking is possible. TR3(1)(e) asks for opportunities to improve rural walking, wheeling, cycling and public transport to be taken; its text does not qualify the (a) test. Some inspectors have accepted less in rural areas: "connectivity opportunities may differ in rural areas" (6009632 ¶17), and infrequent buses were a genuine alternative (6010973 ¶18); both were allowed. A Green Belt permission in principle for up to nine homes was allowed on similar reasoning: reliance on the car for some journeys "is not unusual in a rural context" (6007484 ¶14). Others found failure despite the rural context: "Whilst I acknowledge that in rural areas greater dependency on the private car is a reality, this site is not well connected" (6008693 ¶12; also 6008688 ¶17; 6009718 ¶17). If the route is unsafe or unattractive for some users, the choice is not genuine for them.',
    },
    input: {
      type: 'single',
      options: [
        { value: 'pass', label: 'Yes: a sustainable location' },
        { value: 'fail', label: 'No: residents would be reliant on the private car' },
      ],
    },
    effects: [
      { when: { all: [gate, { eq: ['tr3', 'pass'] }] }, finding: { kind: 'pass', policy: 'GB7(1)(g)(iii)', text: 'A sustainable location with particular reference to TR3.' } },
      {
        when: { all: [gate, { eq: ['tr3', 'fail'] }] },
        finding: { kind: 'fail', policy: 'GB7(1)(g)(iii)', text: 'Not a sustainable location with reference to TR3: the location does not offer a genuine choice of transport modes, so GB7(1)(g) is not met.' },
      },
      { when: { all: [{ not: gate }, { eq: ['tr3', 'pass'] }] }, finding: { kind: 'pass', policy: 'TR3(1)(a)', text: 'The location offers a genuine choice of transport modes (TR3(1)(a)).' } },
      {
        when: { all: [{ not: gate }, { eq: ['tr3', 'fail'] }] },
        finding: { kind: 'harm', policy: 'TR3(1)(a)', text: 'The location would not limit the need to travel by private car or offer a genuine choice of transport modes (TR3(1)(a)).' },
      },
    ],
    cases: { policies: ['GB7(1)(g)(iii)', 'TR3'], groupBy: 'finding', context: ['rural-lane', 'green-belt', 'washed-over-village'], label: 'Sustainable-location findings' },
    contested: {
      summary: 'Is a route acceptable because existing residents already walk it?',
      readings: [
        {
          label: 'Accepted: villagers already cope',
          summary: 'A council decision accepted short unfooted sections in a historic village core because "Villagers appear to cope with this existing situation without any great trouble" (stratford-26-00918-PIP, p.9). On appeal, a footway condition for one home was removed where existing houses relied on the verge with no recorded pedestrian injury collisions (6010706 ¶9), though the inspector accepted this "may well result in access not being suitable for all people" (¶13).',
          cases: { policies: ['GB7(1)(g)(iii)', 'TR3'], tags: ['sustainable-location-pass'], context: ['rural-lane'] },
        },
        {
          label: 'Not enough on its own: use can show necessity, not safety',
          summary: 'Hatton Station (6006637 ¶26): "at least some journeys arise out of necessity rather than choice … the recorded levels of activity do not demonstrate that the route is universally perceived as safe."',
          cases: { policies: ['GB7(1)(g)(iii)', 'TR3'], tags: ['sustainable-location-fail'], context: ['rural-lane'] },
        },
      ],
    },
  },
];
