// The evidence register for the Kington Lane Decision Route (planning application 26/01831/FUL).
//
// DOCS: every document relied on. `ref` is where build.mjs reads the text to check quotations:
//   sources:…  the private sources checkout (text extracts of the council's planning file; not republished)
//   open:…     Crown copyright text held in this repository
// QUOTES: every quotation. `text` must appear in the document, on the page given (PDF page, not the printed number).
// Text read from scanned documents is as the character recognition gave it; choose passages that read cleanly.

const S = (f) => `sources:stratford-dc/claverdon/26-01831-FUL/${f}.txt`;
const FILE = 'https://apps.stratford.gov.uk/Eplanningv2/AppDetail/Index/4935dd70-71fb-cc7d-432a-08deecae750f';
const LDE25 = 'https://apps.stratford.gov.uk/Eplanningv2/AppDetail/Index/9e25a1ce-4015-cd59-b021-08dd6aeda67a';
const DECISION = (id) => `https://planningdistilled.org/research/england/nppf-navigator/decisions/${id}.html`;

export const APPLICATION = {
  ref: '26/01831/FUL',
  authority: 'Stratford-on-Avon District Council',
  site: 'Greenfingers Nurseries, Kington Lane, Claverdon CV35 8PP',
  portal: FILE,
  checked: '6 October 2026',
};

const filed = (name, added) => `Planning file, listed as "${name}", added ${added}`;

export const DOCS = [
  // ----- submitted by the applicant -----
  { key: 'ps', short: 'Planning Statement', title: 'Planning Statement', by: 'Stansgate Planning, for the applicant', dated: '23 July 2026', where: filed('Planning Statement July 2026', '29 July 2026'), url: FILE, group: 'applicant', scanned: true, ref: S('app--20260729--planning-statement-july-2026--5c443b35') },
  { key: 'counsel', short: "Counsel's advice", title: "Advice of leading counsel on previously developed land", by: 'Counsel instructed for the applicant', dated: '17 July 2026', where: filed('P G K C Advice17.7.26', '28 July 2026'), url: FILE, group: 'applicant', scanned: true, ref: S('app--20260728--p-g-k-c-advice17-7-26--58085d67') },
  { key: 'gba', short: 'Green Belt Appraisal', title: 'Green Belt Appraisal (ref DE600_GBA_001B)', by: 'Define, for the applicant', dated: '21 July 2026', where: filed('Buildings/Structures Calculated Volumes D E600 G B A210726', '29 July 2026'), url: FILE, group: 'applicant', ref: S('plan--20260729--buildings-structures-calculated-volumes-d-e600-g-b-a210726--921d0376') },
  { key: 'gba-a', short: 'Existing buildings schedule', title: 'Green Belt Appraisal, Appendix A: existing building footprints and volumes (drawing 24-059-02)', by: 'Beacon Land Surveys, for the applicant', dated: 'October 2024', where: filed('Buildings/Structures Calculated Volumes D E600 G B A Appendix A existing buildings', '29 July 2026'), url: FILE, group: 'applicant', scanned: true, ref: S('plan--20260729--buildings-structures-calculated-volumes-d-e600-g-b-a-appendix-a-existi--13d7749b') },
  { key: 'areas', short: 'Site Areas Schedule', title: 'Site Areas Schedule (drawing 4257): proposed footprints, volumes and site areas', by: 'BHB Architects, for the applicant', dated: 'July 2026', where: filed('Site Areas Schedule 4257', '28 July 2026'), url: FILE, group: 'applicant', ref: S('plan--20260728--site-areas-schedule-4257--ceda5048') },
  { key: 'lva', short: 'Landscape and Visual Appraisal', title: 'Landscape and Visual Appraisal, main text (ref DE600_LVA_001B)', by: 'Define, for the applicant', dated: '21 July 2026', where: filed('Landscape and Visual Assessment Main Text', '29 July 2026'), url: FILE, group: 'applicant', ref: S('app--20260729--landscape-and-visual-assessment-main-text--e94cabfb') },
  { key: 'das3', short: 'Design and Access Statement', title: 'Design and Access Statement, part 3', by: 'BHB Architects, for the applicant', dated: '23 July 2026', where: filed('Design and Access Statement Part 3', '28 July 2026'), url: FILE, group: 'applicant', ref: S('app--20260728--design-and-access-statement-part-3--09e93e8a') },
  { key: 'ta', short: 'Transport Appraisal', title: 'Transport Appraisal, final (ref 25477-02f)', by: 'DTA Transportation, for the applicant', dated: '12 August 2026', where: filed('Transport Appraisal - FINAL 525477-02f', '1 September 2026'), url: FILE, group: 'applicant', ref: S('app--20260901--transport-appraisal-final-525477-02f--c49bb825') },
  { key: 'tn1', short: 'Transport Technical Note 1', title: "Transport Technical Note 1: replies to the Highway Authority's pre-application advice", by: 'DTA Transportation, for the applicant', dated: '25 August 2026', where: filed('Transport Technical Note 1', '1 September 2026'), url: FILE, group: 'applicant', ref: S('app--20260901--transport-technical-note-1--05784bf5') },
  { key: 'fra', short: 'Flood Risk Assessment', title: 'Flood Risk Assessment and Drainage Strategy, part 1 (revision A1-C02)', by: 'JBA Consulting, for the applicant', dated: '21 July 2026', where: filed('Flood Risk Assessment With Appendices Part1', '29 July 2026'), url: FILE, group: 'applicant', scanned: true, ref: S('app--20260729--flood-risk-assessment-with-appendices-part1-r-c-l-j-b-a-x-x-x-x-r-p-h---a7f1dd52') },
  { key: 'evr', short: 'Economic Viability Report', title: 'Economic Viability Report (continued employment use of the site)', by: 'Centrick, for the applicant', dated: 'May 2026', where: filed('Economic Viability Report V3', '29 July 2026'), url: FILE, group: 'applicant', scanned: true, ref: S('app--20260729--economic-viability-report-v3--a141abf8') },
  { key: 'mkt', short: 'Marketing Report', title: 'Marketing Report', by: "The applicant's commercial agents", dated: 'July 2026', where: filed('Marketing Report 260716', '29 July 2026'), url: FILE, group: 'applicant', ref: S('app--20260729--marketing-report-260716--e398fb35') },
  { key: 'ah', short: 'Affordable Housing Options Report', title: 'Affordable Housing Provision Options Report', by: 'Prepared Development Partnerships, for the applicant', dated: '10 November 2025', where: filed('S106 Housing Option Provision Report Final version', '29 July 2026'), url: FILE, group: 'applicant', ref: S('app--20260729--s106-housing-option-provision-report-final-version--9ee07614') },
  { key: 'pea', short: 'Preliminary Ecological Appraisal', title: 'Preliminary Ecological Appraisal, including reptile survey (version 6)', by: 'Cotswold Wildlife Surveys, for the applicant', dated: 'August 2026', where: filed('Preliminary Ecological Appraisal v6', '10 August 2026'), url: FILE, group: 'applicant', scanned: true, ref: S('app--20260810--preliminary-ecological-appraisal-v6--0bb2dc60') },
  { key: 'aia', short: 'Arboricultural Impact Assessment', title: 'Arboricultural Impact Assessment (ref 260527 2169 AIA V1a)', by: 'Wharton, for the applicant', dated: '22 July 2026', where: filed('Arboricultural Assessment', '28 July 2026'), url: FILE, group: 'applicant', scanned: true, ref: S('app--20260728--arboricultural-assessment--d24ee262') },
  { key: 'splay', short: 'Visibility splay tree note', title: 'Arboricultural technical note on the highway visibility splays', by: 'Wharton, for the applicant', dated: '4 September 2026', where: filed('Visibilty Splay Landscape Technical Note', '22 September 2026'), url: FILE, group: 'applicant', ref: S('app--20260922--visibilty-splay-landscape-technical-note--653e34ea') },

  // ----- consultation responses -----
  { key: 'hw', short: 'Highway Authority', title: 'Warwickshire County Council, Highway Authority: consultation response', by: 'Warwickshire County Council (Highways)', dated: '28 September 2026', where: filed('WCC Highways', '28 September 2026'), url: FILE, group: 'consultee', ref: S('consult--20260928--wcc-highways--1253f3a5') },
  { key: 'row', short: 'Rights of Way', title: 'Warwickshire County Council, Rights of Way: consultation response', by: 'Warwickshire County Council (Rights of Way)', dated: 'September 2026', where: filed('WCC Rights of Way', '22 September 2026'), url: FILE, group: 'consultee', scanned: true, ref: S('consult--20260922--wcc-rights-of-way--80700eb8') },
  { key: 'llfa', short: 'Flood Authority', title: 'Warwickshire County Council, Lead Local Flood Authority: consultation response', by: 'Warwickshire County Council (Flood Risk Management)', dated: '23 September 2026', where: filed('LLFA', '25 September 2026'), url: FILE, group: 'consultee', ref: S('consult--20260925--llfa--1ae53b88') },
  { key: 'eco', short: 'County Ecology', title: 'Warwickshire County Council, Ecology: consultation response', by: 'Warwickshire County Council (Ecology)', dated: '25 September 2026', where: filed('WCC Ecology', '25 September 2026'), url: FILE, group: 'consultee', ref: S('consult--20260925--wcc-ecology--00be79e8') },
  { key: 'housing', short: 'Housing officer', title: 'Stratford-on-Avon District Council, Housing Policy and Development Team: consultation response', by: 'Stratford-on-Avon District Council (Housing)', dated: '24 September 2026', where: filed('SDC Policy Housing', '29 September 2026'), url: FILE, group: 'consultee', ref: S('consult--20260929--sdc-policy-housing--5454367b') },
  { key: 'calc', short: 'Off-site contribution calculator', title: 'Off-site affordable housing financial contribution calculator, as run for this application', by: 'Stratford-on-Avon District Council (Housing)', dated: 'September 2026', where: filed('SDC Policy Housing off-site calculation', '29 September 2026'), url: FILE, group: 'consultee', ref: S('consult--20260929--sdc-policy-housing-off-site-calculation--15f97e4f') },
  { key: 'pos', short: 'Open space officer', title: 'Stratford-on-Avon District Council, Public Open Space: consultation response', by: 'Stratford-on-Avon District Council (Public Open Space)', dated: 'September 2026', where: filed('SDC Public Open Space', '30 September 2026'), url: FILE, group: 'consultee', ref: S('consult--20260930--sdc-public-open-space--cfe1fb85') },
  { key: 'pc', short: 'Parish Council', title: 'Claverdon Parish Council: consultation response', by: 'Claverdon Parish Council', dated: '24 September 2026', where: filed('Claverdon Parish Council', '24 September 2026'), url: FILE, group: 'consultee', scanned: true, ref: S('consult--20260924--claverdon-parish-council--81155633') },
  { key: 'ward', short: 'Ward member', title: 'Ward member for Claverdon and Snitterfield: consultation response', by: 'District councillor for the ward', dated: '24 September 2026', where: filed('Cllr D Parker', '24 September 2026'), url: FILE, group: 'consultee', scanned: true, ref: S('consult--20260924--cllr-d-parker--69b83b0c') },

  // ----- council decisions on the site -----
  { key: 'lde-n', short: 'Lawful use certificate', title: 'Certificate of lawful existing use 25/00721/LDE: decision notice', by: 'Stratford-on-Avon District Council', dated: '15 May 2025', where: 'Planning file for 25/00721/LDE, listed as "Decision Letter"', url: LDE25, group: 'council', ref: S('25-00721-LDE--decisi--decision-letter--f6e23a88') },
  { key: 'lde-r', short: 'Lawful use certificate report', title: "Certificate of lawful existing use 25/00721/LDE: officer's delegated report", by: 'Stratford-on-Avon District Council', dated: '15 May 2025', where: 'Planning file for 25/00721/LDE, listed as "Delegated"', url: LDE25, group: 'council', scanned: true, ref: S('25-00721-LDE--report--delegated--4c33ceaf') },

  // ----- policy and appeal decisions -----
  { key: 'nppf', short: 'NPPF', title: 'National Planning Policy Framework, August 2026', by: 'Ministry of Housing, Communities and Local Government', dated: '17 August 2026', where: 'gov.uk', url: 'https://www.gov.uk/government/publications/national-planning-policy-framework--2', group: 'reference', ref: 'open:nppf/NPPF-August-2026.txt' },
  { key: 'np', short: 'Neighbourhood Plan', title: 'Claverdon Neighbourhood Plan 2011 to 2031, made version, with the Village Design Statement at Appendix 1', by: 'Claverdon Parish Council', dated: 'December 2019', where: 'Claverdon Parish Council website', url: 'https://claverdon-pc.gov.uk/wp-content/uploads/2024/09/Claverdon-Neighbourhood-Plan.pdf', group: 'reference', ref: 'sources:stratford-dc/claverdon/Claverdon-Neighbourhood-Plan.txt' },
  { key: 'a-6011972', short: 'Appeal 6011972', title: 'Appeal decision 6011972, Wire Mill Lane, Newchapel, Surrey (eight houses on an equestrian site)', by: 'Planning Inspectorate', dated: '18 September 2026', where: 'Planning Distilled decision note', url: DECISION('PINS-6011972'), group: 'reference', ref: 'open:pins-corpus/6011972.txt' },
  { key: 'a-6011330', short: 'Appeal 6011330', title: 'Appeal decision 6011330, Cowley Lane, Dronfield, Derbyshire (one house replacing equestrian buildings)', by: 'Planning Inspectorate', dated: '15 September 2026', where: 'Planning Distilled decision note', url: DECISION('PINS-6011330'), group: 'reference', ref: 'open:pins-corpus/6011330.txt' },
  { key: 'a-6006637', short: 'Appeal 6006637', title: 'Appeal decision 6006637, Hatton Station, Warwick (28 affordable homes)', by: 'Planning Inspectorate', dated: '23 September 2026', where: 'Planning Distilled decision note', url: DECISION('PINS-6006637'), group: 'reference', ref: 'open:pins-corpus/6006637.txt' },
  { key: 'a-6010729', short: 'Appeal 6010729', title: 'Appeal decision 6010729, Roche Road, St Austell, Cornwall (holiday accommodation with a flood-prone access)', by: 'Planning Inspectorate', dated: '8 September 2026', where: 'Planning Distilled decision note', url: DECISION('PINS-6010729'), group: 'reference', ref: 'open:pins-corpus/6010729.txt' },
  { key: 'a-6010313', short: 'Appeal 6010313', title: 'Appeal decision 6010313, Brickhouse Lane, Newchapel, Surrey (five houses)', by: 'Planning Inspectorate', dated: '4 September 2026', where: 'Planning Distilled decision note', url: DECISION('PINS-6010313'), group: 'reference', ref: 'open:pins-corpus/6010313.txt' },
];

export const TOPICS = [
  { key: 'case', title: "The applicant's case and the Framework it was written to" },
  { key: 'pdl', title: 'Previously developed land' },
  { key: 'openness', title: 'Openness of the Green Belt' },
  { key: 'location', title: 'Location and the walking route' },
  { key: 'access', title: 'Access, traffic and highway safety' },
  { key: 'gb8', title: 'Affordable housing and the Golden Rules' },
  { key: 'flood', title: 'Flood risk and drainage' },
  { key: 'nature', title: 'Ecology, trees and hedgerows' },
  { key: 'design', title: 'Landscape, character, design and heritage' },
  { key: 'plan', title: 'Development plan and employment land' },
  { key: 'framework', title: 'The Framework' },
  { key: 'appeals', title: 'Appeal decisions' },
];

export const QUOTES = [
  // ---------- the applicant's case ----------
  { id: 'ps-framework', topic: 'case', doc: 'ps', page: 8, para: '5.3', text: 'National Planning Policy Framework December 2024' },
  { id: 'ps-route-e', topic: 'case', doc: 'ps', page: 36, para: '10.4', text: 'The principle of redeveloping this site is policy-compliant with paragraph 154g) of the Framework, which allows for the redevelopment of PDL, where there is no substantial harm to the openness of the Green Belt.' },
  { id: 'ps-route-g', topic: 'case', doc: 'ps', page: 36, para: '10.5', text: 'then the site can reasonably be considered as a grey belt site and the scheme meets the requirements of paragraphs 155 - 157 of the Framework' },
  { id: 'ps-route-vsc', topic: 'case', doc: 'ps', page: 36, para: '10.6', text: 'then the Council must conclude that the proposals amount to inappropriate development within the Green Belt' },
  { id: 'ps-11d', topic: 'case', doc: 'ps', page: 36, para: '10.1', text: 'The Council can no longer demonstrate a five year supply of housing and paragraph 11d) of the Framework is engaged.' },
  { id: 'ps-harm-definition', topic: 'case', doc: 'ps', page: 24, para: '7.29', text: 'In this case, the harm to the Green Belt is harm by way of definition only, with no other harms identified.' },
  { id: 'ps-preapp', topic: 'case', doc: 'ps', page: 5, para: '3.1', text: 'it was accepted that this is not a greenfield site and that it can be considered as a grey belt site if it can be demonstrated that the location is sustainable' },
  { id: 'ps-ev', topic: 'case', doc: 'ps', page: 20, para: '7.17', text: 'Each new home will be provided with an electric vehicle charging point (EVCP), with zero emission vehicles being recognised in Annex 2: Glossary of the Framework as a sustainable transport mode.' },
  { id: 'ps-para110', topic: 'case', doc: 'ps', page: 20, para: '7.16', text: 'with paragraph 110 acknowledging that opportunities to maximise sustainable transport solutions will vary between urban and rural areas' },
  { id: 'ps-golden-weight', topic: 'case', doc: 'ps', page: 24, para: '7.28', text: 'The scheme will comply with the Golden Rules and this should be given significant weight in favour of granting planning permission (paragraph 158 of the Framework).' },
  { id: 'ps-homes-weight', topic: 'case', doc: 'ps', page: 37, para: '10.8', text: "The provision of 10 dwellings towards the Council's acknowledged shortfall in supply should be given significant weight in the planning balance." },
  { id: 'ta-framework', topic: 'case', doc: 'ta', page: 2, para: '2.1.1', text: 'The revised National Planning Policy Framework (NPPF) was published in December 2024' },
  { id: 'fra-framework', topic: 'case', doc: 'fra', page: 13, para: '3.1', text: 'most recently revised in December 2024' },

  // ---------- previously developed land ----------
  { id: 'counsel-officer-1', topic: 'pdl', doc: 'counsel', page: 3, para: '8, quoting the pre-application response', text: 'Whilst part of the site could be considered as PDL, the extent would need to be demonstrated at application stage as any parts of the site in horticultural (agricultural) use would not be PDL.' },
  { id: 'counsel-officer-2', topic: 'pdl', doc: 'counsel', page: 4, para: '9, quoting the pre-application response', text: 'As such, any area of the site in agricultural use is not considered to be PDL.' },
  { id: 'counsel-area', topic: 'pdl', doc: 'counsel', page: 1, para: '2', text: 'The Site extends to approximately 1.84 hectares' },
  { id: 'counsel-scope', topic: 'pdl', doc: 'counsel', page: 4, para: '10', text: 'My advice is sought solely upon whether those observations are correct' },
  { id: 'counsel-2024', topic: 'pdl', doc: 'counsel', page: 4, para: '10', text: 'the 2024 edition of the National Planning Policy Framework' },
  { id: 'counsel-view', topic: 'pdl', doc: 'counsel', page: 4, para: '12', text: "I do not consider that the officer's observations (as set out in paragraphs 8 and 9 above) are correct and that the Site does constitute previously developed land" },
  { id: 'counsel-unit', topic: 'pdl', doc: 'counsel', page: 7, para: '22', text: 'Its use is accepted to be a mixed-use over the entirety of the Site. There is no basis for a subdivision of the sort that arose in Lee Valley.' },
  { id: 'counsel-lee-valley-north', topic: 'pdl', doc: 'counsel', page: 5, para: '16', text: 'the northern part of the site was conceded not to be previously developed land' },
  { id: 'counsel-lee-valley-alone', topic: 'pdl', doc: 'counsel', page: 6, para: '17, quoting the judgment', text: 'in my view mean a building used for the purposes of agriculture alone' },
  { id: 'counsel-accepted', topic: 'pdl', doc: 'counsel', page: 8, para: '22', text: 'These buildings on the Site (and the hardstanding areas) are accepted to be no longer used for agricultural purposes alone.' },
  { id: 'ps-pdl-whole', topic: 'pdl', doc: 'ps', page: 9, para: '6.4', text: 'The whole of the site is therefore previously developed land.' },
  { id: 'lde-notice', topic: 'pdl', doc: 'lde-n', page: 1, text: 'A limited functional relationship is identified between the two primary growing and storage operations, resulting in two materially different uses occurring. When combining these factors, the uses as presented, are separate within the site.' },
  { id: 'lde-closed', topic: 'pdl', doc: 'lde-r', page: 5, text: 'This area had further greenhouses/polytunnels and there was a small area used for the growing of very immature plants in plug trays' },
  { id: 'lde-area', topic: 'pdl', doc: 'lde-r', page: 7, text: 'Around 17-25% of the site area is used for the growing of plants (cover letter)' },
  { id: 'lde-east', topic: 'pdl', doc: 'lde-r', page: 7, para: "quoting the applicant's statutory declaration", text: 'the western part of the site has primarily been used for plant sales and the processing and storage of imported plants, and the eastern part primarily used as a nursery production area' },
  { id: 'lde-third', topic: 'pdl', doc: 'lde-r', page: 7, text: 'This presents a claim that around one third of the site has been used for agricultural uses.' },
  { id: 'lde-substantial', topic: 'pdl', doc: 'lde-r', page: 7, text: 'it is clear that there is a substantial agricultural operation occurring at the site currently' },
  { id: 'lde-repurposed', topic: 'pdl', doc: 'lde-r', page: 6, text: 'suggesting that the structures have been re-purposed for storage rather than growing' },
  { id: 'lde-tunnels', topic: 'pdl', doc: 'lde-r', page: 4, para: 'planning history, 92/00782/FUL', text: 'single span polythene tunnels for the production of horticultural crops' },
  { id: 'lde-conclusion', topic: 'pdl', doc: 'lde-r', page: 12, text: 'with a smaller but by no means insignificant use of horticulture continuing on site' },
  { id: 'gba-a-total', topic: 'pdl', doc: 'gba-a', page: 1, text: '3,892.02 m2 11,730.4 m3', note: 'The schedule lists 21 structures. Eleven rows are polytunnels (3,302.82 square metres and 9,511.3 cubic metres in total) and one is a glasshouse (358.75 square metres and 1,631.7 cubic metres). Together they are 94% of the footprint and 95% of the volume. The remaining nine rows (a portacabin, a canopy, sheds, toilets, offices and a tank) total about 230 square metres and 587 cubic metres. The totals are our addition of the rows on the drawing.' },
  { id: 'gba-a-largest', topic: 'pdl', doc: 'gba-a', page: 1, para: 'row 10', text: '1,159.16 3,656' },
  { id: 'gba-a-glasshouse', topic: 'pdl', doc: 'gba-a', page: 1, para: 'row 17', text: 'Glass-house 358.75 1,631.7' },

  // ---------- openness ----------
  { id: 'gba-existing', topic: 'openness', doc: 'gba', page: 8, para: '3.1.6', text: 'The existing site buildings create a footprint total of 3,892m2 and a volume of 11,730m3 (see Appendix A of this report). The overall average massing height of the existing buildings is just over 3 metres.' },
  { id: 'gba-heights', topic: 'openness', doc: 'gba', page: 9, para: '3.1.9', text: 'The heights of the buildings to be constructed on the site would vary between 5m and 8m in height.' },
  { id: 'gba-change', topic: 'openness', doc: 'gba', page: 9, text: 'Overall, built-form coverage within the site would decrease by 47% and the volume of development within the site would decrease by 9.5% (11,730m3 decreasing to 10,607m3).' },
  { id: 'gba-none', topic: 'openness', doc: 'gba', page: 9, text: 'the level of harm of the proposed development on spatial openness would be None' },
  { id: 'gba-visual-none', topic: 'openness', doc: 'gba', page: 11, para: '3.2.10', text: 'it is concluded that the level of harm to visual openness arising from the proposed development would be None' },
  { id: 'gba-method', topic: 'openness', doc: 'gba', page: 6, para: 'Table 2.1', text: 'A considerable increase to development within the site which, in the context of the proposed development, is deemed to equate to a >25% increase to built volume.' },
  { id: 'gba-taller', topic: 'openness', doc: 'gba', page: 11, para: '3.2.7', text: 'The height of the proposed buildings would be greater than those currently located on the site, however the massing of built form would be reduced.' },
  { id: 'gba-upper', topic: 'openness', doc: 'gba', page: 11, para: '3.2.9', text: 'only the upper parts (i.e. first floors and/or roofs) would be perceptible' },
  { id: 'gba-visible', topic: 'openness', doc: 'gba', page: 11, para: '3.2.7', text: 'The proposed development would be visible in views from the footpaths and bridleway to the east of the site.' },
  { id: 'gba-separate', topic: 'openness', doc: 'gba', page: 8, para: '3.1.7', text: 'the proposed development would be physically separate from the village of Claverdon to the east' },
  { id: 'gba-edge', topic: 'openness', doc: 'gba', page: 3, para: '1.2.1', text: 'The site is located just beyond the western edge of the village of Claverdon.' },
  { id: 'areas-footprint', topic: 'openness', doc: 'areas', page: 1, text: 'Total Combined Footprint 2033.98' },
  { id: 'areas-volume', topic: 'openness', doc: 'areas', page: 1, text: 'Total Combined Volume 10607.09' },
  { id: 'areas-site', topic: 'openness', doc: 'areas', page: 1, text: 'Total Site Area 19,772' },
  { id: 'areas-hard', topic: 'openness', doc: 'areas', page: 1, text: 'Total Hard Standing 3765.3' },
  { id: 'areas-gardens', topic: 'openness', doc: 'areas', page: 1, para: 'totals row: house footprint, house volume, garage footprint, garage volume, rear gardens', text: '1785.94 9557.69 248.04 1049.4 4001.1' },
  { id: 'areas-pos', topic: 'openness', doc: 'areas', page: 1, text: 'Public Open Space (m2) 4503' },
  { id: 'lva-panoramic', topic: 'openness', doc: 'lva', page: 23, para: '6.3.9', text: 'Panoramic, elevated views of the proposed development would be available from this path' },
  { id: 'ps-covered', topic: 'openness', doc: 'ps', page: 4, para: '2.5', text: 'The existing site is almost entirely covered by hardstanding and a number of large buildings and other structures' },

  // ---------- location ----------
  { id: 'hw-objects', topic: 'location', doc: 'hw', page: 1, text: 'the Highway Authority objects to the planning application' },
  { id: 'hw-unsustainable', topic: 'location', doc: 'hw', page: 1, text: 'The application site is located within a rural and inherently unsustainable location' },
  { id: 'hw-lane', topic: 'location', doc: 'hw', page: 1, text: 'Kington Lane is characterised as a narrow, single-lane rural route with limited opportunity for passing and no associated footway, street lighting or parking restrictions in the vicinity.' },
  { id: 'hw-distance', topic: 'location', doc: 'hw', page: 2, text: 'The site is not located within reasonable walking distance of day-to-day services, facilities or public transport infrastructure. The nearest bus stops and bus services are located approximately 1km from the site, whilst Claverdon Railway Station is approximately 2.5km away. Access to these facilities would require pedestrians to travel along rural roads without the benefit of footways or street lighting.' },
  { id: 'hw-carriageway', topic: 'location', doc: 'hw', page: 2, text: 'There are no dedicated footways linking the site to local facilities, public transport or services. As a result, pedestrians would be required to walk within the carriageway of Kington Lane, which is unlit and rural in character.' },
  { id: 'hw-vulnerable', topic: 'location', doc: 'hw', page: 2, text: 'This is particularly relevant for vulnerable users, including children, older persons and those travelling during periods of darkness or adverse weather conditions.' },
  { id: 'hw-henley', topic: 'location', doc: 'hw', page: 3, para: 'Active Travel', text: 'The footway along Henley road is very narrow at points, for example alongside Bankside Cottage where the speed limit remains 50mph, and does not provide an accessible route into the village. It is well below the 2m standard width and too narrow for a pushchair/buggy to be easily accommodated.' },
  { id: 'hw-active-travel', topic: 'location', doc: 'hw', page: 3, para: 'Active Travel', text: 'This application is not sustainable from an active travel perspective. There are no suitable and accessible pedestrian routes into Claverdon which will lead to a reliance on motor vehicles for short journeys.' },
  { id: 'hw-link-lines', topic: 'location', doc: 'hw', page: 3, text: 'However, this land has not been identified within either the red-line application boundary or the blue-line ownership plan.' },
  { id: 'hw-link-deliverable', topic: 'location', doc: 'hw', page: 4, para: 'Active Travel', text: 'Nor is it a public right of way and no permanent access over it can be guaranteed. The surface is rough and not fully accessible. For these reasons it cannot be considered as contributing to active travel access to the development.' },
  { id: 'hw-bridleway', topic: 'location', doc: 'hw', page: 3, para: 'Active Travel', text: 'The bridleway SD340/1 does provide a link into Claverdon, however it is overgrown and its width is uncertain.' },
  { id: 'hw-bus-stops', topic: 'location', doc: 'hw', page: 4, para: 'Active Travel', text: 'The developer would need to provide a pair of bus stops with hard standing on Henley Road at the junction with Kington Lane' },
  { id: 'hw-passing', topic: 'location', doc: 'hw', page: 3, para: 'Active Travel', text: 'Formal passing/waiting places must be provided.' },
  { id: 'hw-2011', topic: 'location', doc: 'hw', page: 2, text: 'However, planning policy and the emphasis placed upon sustainable travel have evolved, and it is appropriate to consider such matters in the assessment of the current proposal.' },
  { id: 'hw-tr3', topic: 'location', doc: 'hw', page: 2, text: 'the proposal is considered contrary to the principles of sustainable development and the requirements of Local Plan Policy TR3, which seeks to locate development where sustainable travel choices are available and realistic' },
  { id: 'ta-lane', topic: 'location', doc: 'ta', page: 5, para: '4.2.1', text: 'Kington Lane is principally an unlit rural lane serving numerous dwellings, agricultural holdings and commercial development. It is single lane width' },
  { id: 'ta-limit', topic: 'location', doc: 'ta', page: 5, para: '4.2.2', text: 'It is subject to the national speed limit (60mph)' },
  { id: 'ta-count', topic: 'location', doc: 'ta', page: 6, para: '4.2.3', text: 'An automatic traffic count (ATC) was deployed on Kington Lane between Friday 17th October and Thursday 23rd October 2025.' },
  { id: 'ta-speeds-ne', topic: 'location', doc: 'ta', page: 28, para: 'Appendix C, north-eastbound week summary', text: 'Fri 17-Oct-25 Thu 23-Oct-25 1020 161 146 31.4 24.8', note: 'The columns are the week total, the five-day average flow, the seven-day average flow, the 85th percentile speed and the mean speed, in miles per hour. The south-westbound row gives 153, 140, 30.6 and 25.3.' },
  { id: 'ta-speeds-max', topic: 'location', doc: 'ta', page: 52, para: 'Appendix C, north-eastbound daily speeds', text: 'Wed 22-Oct-25 155 32.3', note: 'The highest daily 85th percentile speed in the survey week: 32.3 miles per hour.' },
  { id: 'ta-footway', topic: 'location', doc: 'ta', page: 7, para: '4.3.3', text: 'There is a footway at the junction of Kington Lane and the A4189 Henley Road that connects into the village' },
  { id: 'ta-bus', topic: 'location', doc: 'ta', page: 7, para: '4.3.6', text: 'Claverdon is also served by the 510 & 511 bus services Monday-Friday however, these are limited services only serving the village once a day from near to the Church.' },
  { id: 'ta-isochrone', topic: 'location', doc: 'ta', page: 7, para: '4.3.8', text: 'all facilities within the village with the exception of the railway station is within 2km of the site' },
  { id: 'ta-link', topic: 'location', doc: 'ta', page: 7, para: '4.3.2', text: 'As part of the development proposals, a link will be delivered to connect to this pathway across the field to the east of the development' },
  { id: 'ps-footpath', topic: 'location', doc: 'ps', page: 5, para: '4.2', text: 'There is a footpath on this side of Henley Road, connecting the site with the community facilities within the village.' },
  { id: 'ps-car', topic: 'location', doc: 'ps', page: 20, para: '7.18', text: 'recognising that most families will be reliant on a car for most of their journeys' },
  { id: 'ps-bus-limited', topic: 'location', doc: 'ps', page: 20, para: '7.17', text: 'Bus services can be picked up along Henley Road and from bus stops within the village, but it is recognised that these are limited services.' },
  { id: 'ps-not-isolated', topic: 'location', doc: 'ps', page: 6, para: '4.4', text: 'This is, therefore, not an isolated location within open countryside.' },
  { id: 'evr-isolated', topic: 'location', doc: 'evr', page: 38, para: '4.4', text: "Office and training centre use (Use Class E) is not viable due to the site's rural and isolated location, lack of meaningful public transport connectivity." },
  { id: 'evr-distance', topic: 'location', doc: 'evr', page: 8, para: '2.1.2', text: 'The subject site is situated approximately 0.6 miles (1.0 km) from Claverdon village' },
  { id: 'ah-location', topic: 'location', doc: 'ah', page: 11, para: 'section 4', text: 'In addition, affordable housing requires closer and more substantial local amenities and transport links, which isn’t the case for commuters who live in the Village.' },
  { id: 'row-link', topic: 'location', doc: 'row', page: 1, text: "If the proposed path crosses or leads onto land outside of the applicant's control then we also recommend that the applicant obtains the consent of the relevant landowners" },
  { id: 'ward-car', topic: 'location', doc: 'ward', page: 1, text: 'There is no, realistic, means of accessing services other than by car.' },
  { id: 'pc-tr3', topic: 'location', doc: 'pc', page: 3, para: '2.3', text: 'CPC has concluded that, on balance, the site is not in a sustainable location, with particular reference to NPPF Policy TR3' },

  // ---------- access, traffic and highway safety ----------
  { id: 'hw-conclusion', topic: 'access', doc: 'hw', page: 6, para: 'Conclusion', text: 'Based on the analysis of the information submitted the Highway Authority concludes that there would be unacceptable impact to pedestrian safety and therefore recommends that this application is refused.' },
  { id: 'hw-access-ok', topic: 'access', doc: 'hw', page: 1, text: 'The site benefits from an existing shared vehicular access, which appears capable of providing acceptable visibility in both directions' },
  { id: 'hw-trips', topic: 'access', doc: 'hw', page: 6, text: 'The trips being generated are low and comparable in comparison to the existing business and therefore the wider network will not be impacted by this proposed development with the added benefits of HGVs previously serving the site being removed due to the proposed change of use.' },
  { id: 'hw-address', topic: 'access', doc: 'hw', page: 2, text: 'The applicant should address the concerns identified below or provide robust evidence and justification where they disagree with the recommendations made.' },
  { id: 'ta-existing-trips', topic: 'access', doc: 'ta', page: 11, para: '5.5.1', text: 'the site generated c54 (27 in and 27 out) vehicle movements per day' },
  { id: 'ta-proposed-trips', topic: 'access', doc: 'ta', page: 12, para: '5.5.6', text: 'the proposals at worst would generate six vehicle movements in the peak hour and a total of 63 throughout the day' },
  { id: 'ta-hgv', topic: 'access', doc: 'ta', page: 12, para: '5.5.3', text: 'on average there are 1-2 articulated HGV movements per week' },
  { id: 'ta-reduce', topic: 'access', doc: 'ta', page: 13, para: '6.4', text: 'The development would benefit the surrounding highway network by removing the existing HGV traffic associated to the site and would reduce overall daily traffic figures.' },
  { id: 'ta-collisions', topic: 'access', doc: 'ta', page: 8, para: '4.4.1', text: 'there have been no recorded collisions in the submitted search area' },
  { id: 'tn1-footway', topic: 'access', doc: 'tn1', page: 4, para: "4.0, the Highway Authority's pre-application comment", text: 'A short section of footway is proposed within the bellmouth access arrangement; however, this does not connect to any existing footway provision on Kington Lane. This could cause uncertainty for pedestrians.' },
  { id: 'tn1-contributions', topic: 'access', doc: 'tn1', page: 5, para: '5.1', text: 'the applicant would be willing to provide fair and reasonable financial contributions towards ongoing maintenance and upgrades to the local network' },
  { id: 'tn1-private', topic: 'access', doc: 'tn1', page: 4, para: '4.2', text: 'the development is to remain private with future residents being aware of the access arrangements to the site' },
  { id: 'ta-gates', topic: 'access', doc: 'ta', page: 9, para: '5.2.2', text: 'these will be retained in their current form' },

  // ---------- affordable housing and the Golden Rules ----------
  { id: 'ps-golden', topic: 'gb8', doc: 'ps', page: 22, para: '7.23', text: 'it will provide an off-site contribution equivalent to 50% affordable housing as part of the proposals, and it will deliver any necessary improvements to local infrastructure along with accessible public green spaces' },
  { id: 'ps-hots', topic: 'gb8', doc: 'ps', page: 1, para: 'title page', text: 'draft S106 HoTs' },
  { id: 'ps-s106-timeline', topic: 'gb8', doc: 'ps', page: 41, para: 'Appendix 1', text: 'S106 signed and planning permission granted' },
  { id: 'ps-pos-sum', topic: 'gb8', doc: 'ps', page: 35, para: '9.19', text: "An off-site sum towards allotments and equipped childrens' play will be secured by S106 agreement." },
  { id: 'ah-negotiate', topic: 'gb8', doc: 'ah', page: 12, para: 'section 5', text: 'PDP recommend that the Applicants and SDC negotiate a viable offsite monetary contribution in lieu of the delivery of onsite affordable housing provision' },
  { id: 'ah-deadline', topic: 'gb8', doc: 'ah', page: 9, para: 'section 4', text: 'PDP provided a deadline of Wednesday 12th November 2025 for Expressions of Interest' },
  { id: 'ah-reasons', topic: 'gb8', doc: 'ah', page: 9, para: 'section 4', text: 'The key four reasons provided is that five dwellings is too few units to warrant any interest' },
  { id: 'ps-preapp-date', topic: 'gb8', doc: 'ps', page: 5, para: '3.1', text: 'A pre-application enquiry was submitted to the Council in December 2025' },
  { id: 'ah-negative', topic: 'gb8', doc: 'ah', page: 9, para: 'section 4', text: 'PDP has received a negative response from all 13 Affordable Housing Providers' },
  { id: 'housing-popular', topic: 'gb8', doc: 'housing', page: 1, para: '1.2', text: 'we are satisfied that Claverdon would be a popular location for prospective tenants/purchasers given the scale of development proposed in this case' },
  { id: 'housing-six', topic: 'gb8', doc: 'housing', page: 1, para: '1.4', text: 'only a very limited supply of such housing: 6 homes in total' },
  { id: 'housing-onsite', topic: 'gb8', doc: 'housing', page: 2, para: '2.9', text: 'we recommend that careful consideration should be given as to whether: (a) on-site affordable housing provision would instead be appropriate, and (b) whether the application of NPPF Policy GB8 would result in a 50% affordable housing requirement' },
  { id: 'housing-five', topic: 'gb8', doc: 'housing', page: 2, para: '2.10', text: 'we recommend that a off-site financial contribution should be sought equating to 50% of the total housing provision proposed: in other words, a contribution equivalent to 5 dwellings' },
  { id: 'housing-engagement', topic: 'gb8', doc: 'housing', page: 2, para: '2.6', text: 'As this matter will affect the prospects for timely delivery, you will need to take this into account when reaching the necessary overall planning balance on the application.' },
  { id: 'calc-rate', topic: 'gb8', doc: 'calc', page: 1, text: 'Affordable housing requirement 35%' },
  { id: 'calc-total', topic: 'gb8', doc: 'calc', page: 1, text: 'Gross contribution £274,750.00', note: 'The sheet multiplies 3.5 homes by a base figure of £78,500 for the district outside Stratford-upon-Avon, and says contributions are indexed from 1 April 2017. At the five homes the housing officer recommends, the same base figure gives £392,500 before indexation. That figure is our arithmetic and is not stated in any document on the file.' },
  { id: 'calc-base', topic: 'gb8', doc: 'calc', page: 1, text: 'Rest of District £ 78,500' },
  { id: 'pos-exceeds', topic: 'gb8', doc: 'pos', page: 3, text: 'The provision of 4,503m2 of public open space (source: Design and Access Statement) exceeds the minimum required (612.51m2) by a significant margin' },
  { id: 'evr-scope', topic: 'gb8', doc: 'evr', page: 5, para: '1.1.2', text: "We have been instructed by the site owner to assess whether the existing lawful use of the Site and other reasonable alternative commercial uses are economically viable" },

  // ---------- flood risk ----------
  { id: 'fra-zone1', topic: 'flood', doc: 'fra', page: 18, para: '4.2', text: 'the entire site is located within Flood Zone 1' },
  { id: 'fra-surface', topic: 'flood', doc: 'fra', page: 19, para: '4.3.1', text: 'The site and its access from Kington Lane are at high to low risk of surface water flooding.' },
  { id: 'fra-depth', topic: 'flood', doc: 'fra', page: 23, para: '4.3.2.3', text: 'Access to the site is provided via Kington Lane, which is modelled to host flood depths of 0.19m.' },
  { id: 'fra-hazard', topic: 'flood', doc: 'fra', page: 28, para: '5.3', text: 'During the design 1%AEP+CC event the junction is predicted to flood with hazard of Danger for Some /Danger for Most category.' },
  { id: 'fra-emergency', topic: 'flood', doc: 'fra', page: 28, para: '5.3', text: 'Any flooding of such magnitude would be temporary and thus the access would not be impeded for a long time. Emergency services access would still be possible.' },
  { id: 'fra-llfa-said', topic: 'flood', doc: 'fra', page: 28, para: '5.3', text: 'the LLFA have advised during the consultation meeting that the above would not be a reason for objection to the scheme' },
  { id: 'fra-forecasts', topic: 'flood', doc: 'fra', page: 44, para: '8.1', text: 'Future site users/ occupiers should however take account of weather forecasts and avoid travelling in particularly wet weather conditions.' },
  { id: 'fra-outside', topic: 'flood', doc: 'fra', page: 26, para: '4.3.3', text: 'No developable area and no ground level modifications are proposed within the surface water flood risk area' },
  { id: 'fra-floors', topic: 'flood', doc: 'fra', page: 28, para: '5.1', text: 'A minimum FFL of 98.01mAOD will satisfy this recommendation.' },
  { id: 'fra-sequential', topic: 'flood', doc: 'fra', page: 15, para: '3.3', text: 'It is normally required if any part of the site (including access routes, land raising, or vulnerable uses) lies in an area at risk of flooding.' },
  { id: 'fra-foul', topic: 'flood', doc: 'fra', page: 8, para: 'Executive Summary', text: 'The development will be served by a private packaged foul water treatment plant discharging to the watercourse to the south of the site.' },
  { id: 'llfa-principles', topic: 'flood', doc: 'llfa', page: 3, text: 'Whilst the applicant has demonstrated the principles of an acceptable surface water management strategy at the site, further information is still required as detailed above.' },
  { id: 'llfa-infiltration', topic: 'flood', doc: 'llfa', page: 1, para: 'Condition 1', text: 'Undertake infiltration testing in accordance with the BRE 365 guidance' },
  { id: 'llfa-third-party', topic: 'flood', doc: 'llfa', page: 1, para: 'Condition 1', text: 'further information should be provided regarding the ownership, purpose, location and condition of this asset along with confirmation of the right to connect into it' },

  // ---------- ecology, trees and hedgerows ----------
  { id: 'eco-further', topic: 'nature', doc: 'eco', page: 3, text: 'Further ecological information is required, prior to determination, as outlined below:' },
  { id: 'eco-surveys', topic: 'nature', doc: 'eco', page: 2, text: 'WCC Ecology are satisfied with the protected species survey effort described in the PEA report and with the general conclusions of the report.' },
  { id: 'eco-h5', topic: 'nature', doc: 'eco', page: 2, text: 'However, the loss of hedgerow H5 is not accounted for in the metric spreadsheet. It is recommended that a revised metric spreadsheet is provided, prior to determination, to accurately account for hedgerow loss.' },
  { id: 'eco-ten', topic: 'nature', doc: 'eco', page: 2, text: 'WCC Ecology are satisfied that the proposed development can likely achieve the statutory 10% BNG in habitat units and watercourse units' },
  { id: 'eco-enhance', topic: 'nature', doc: 'eco', page: 2, text: 'No ecological enhancement recommendations have been provided in the PEA report.' },
  { id: 'pea-reptiles', topic: 'nature', doc: 'pea', page: 7, para: 'Summary', text: 'Up to four Common Lizards and two juvenile Grass Snakes were recorded' },
  { id: 'pea-relocate', topic: 'nature', doc: 'pea', page: 31, para: '4.2', text: 'Any reptiles trapped will be relocated into the retained natural area at the western end of the site.' },
  { id: 'pea-gain', topic: 'nature', doc: 'pea', page: 34, para: '4.4', text: 'This confirms a gain of 57.47% in habitat units, an 11.55% gain in hedgerow units, and a 12.0% gain in watercourse units.' },
  { id: 'ps-gain', topic: 'nature', doc: 'ps', page: 34, para: '9.11', text: '13% increase in hedgerow units' },
  { id: 'ps-gain-weight', topic: 'nature', doc: 'ps', page: 37, para: '10.8', text: 'The biodiversity net gains, which are substantially more than the required 10%, should be given moderate weight in support of the application.' },
  { id: 'aia-g4', topic: 'nature', doc: 'aia', page: 13, para: '6.6.5', text: 'To implement the new proposed plot garden fence boundaries, there will be a requirement to remove a low-quality C category group, G4.' },
  { id: 'aia-retained', topic: 'nature', doc: 'aia', page: 20, para: '8.1.9', text: 'This balance has secured the retention of all moderate and high value individual trees across the Site' },
  { id: 'aia-services', topic: 'nature', doc: 'aia', page: 15, para: '6.7.16', text: 'there is insufficient information relating to below ground infrastructure available at present' },
  { id: 'aia-tpo', topic: 'nature', doc: 'aia', page: 8, para: '4.1.2', text: 'there are no TPOs charged on the land and the Site does not sit within a Conservation Area' },
  { id: 'aia-absent', topic: 'nature', doc: 'aia', page: 8, para: '4.1.7', text: 'The Site was absent of these non-statutory designations.' },
  { id: 'aia-t20', topic: 'nature', doc: 'aia', page: 34, para: 'tree schedule, row T20', text: '>40 years A1 707 15.0', note: 'Row T20 of the tree schedule, read by eye from the page image because the table did not survive text recognition: common ash, height 18 metres, stem diameter 1,250 millimetres, age class "Vet", physiological condition fair, structural condition poor, estimated remaining contribution over 40 years, category A1, root protection area 707 square metres, radius 15.0 metres. The notes end "High habitat potential".' },
  { id: 'aia-buffer', topic: 'nature', doc: 'aia', page: 27, para: 'survey method notes', text: "Fifteen times the diameter of its stem or 5m from the edge of its canopy" },
  { id: 'aia-veteran-rpa', topic: 'nature', doc: 'aia', page: 29, para: 'notes to the tree schedule', text: 'Where veteran trees have been identified the RPA has been calculated in accordance with Natural England guidance' },
  { id: 'splay-g8', topic: 'nature', doc: 'splay', page: 2, text: 'It has been determined that c. 20-30 m of the understory within G8 will require a level of pruning to facilitate the proposed visibility splay and achieve the necessary visibility requirements.' },
  { id: 'splay-t23', topic: 'nature', doc: 'splay', page: 2, text: 'It is recommended that T23, an early mature common ash, is removed on health and safety grounds.' },
  { id: 'gba-no-vegetation', topic: 'nature', doc: 'gba', page: 9, para: '3.1.8', text: 'No vegetation would be removed as a result of the proposed development, save for an ornamental hedgerow adjoining the western section of the access road to the development.' },

  // ---------- landscape, character, design and heritage ----------
  { id: 'lva-valued', topic: 'design', doc: 'lva', page: 12, para: '3.9.4', text: 'the site itself is not considered to be a valued landscape (as defined in the NPPF and TGN02/21) but is considered to be located within a valued landscape due it being located in the Arden SLA' },
  { id: 'lva-neutral', topic: 'design', doc: 'lva', page: 18, para: '5.4.3', text: 'the Proposed Development is accordingly appraised to have a moderate to minor and neutral overall effect on this receptor at completion (year 1) and at year 15' },
  { id: 'lva-views', topic: 'design', doc: 'lva', page: 28, para: '7.5.2', text: 'The proposed development would be visible in views B2 and B4 within valued landscape B as defined in the CNP. However, the proposed development would not materially alter the characteristics or qualities of these views.' },
  { id: 'lva-heritage', topic: 'design', doc: 'lva', page: 10, para: '3.6.2', text: 'There are no listed assets within the site or its immediate surroundings. There is a listed building (Fox Hill) located along Henley Road, circa 475m north east of the site.' },
  { id: 'das-preapp', topic: 'design', doc: 'das3', page: 5, text: 'the officer commented on the cul-de-sac layout which was considered quite domestic and suburban for a rural location, whilst the scale of the proposed dwellings also raised concern, noting the high number of 2 storey, 5-bedroom dwellings' },
  { id: 'ward-character', topic: 'design', doc: 'ward', page: 1, text: 'The Suburban style development proposed is an unwelcome departure from the current evolution of the hamlet and is outside the village BUAB, in green belt, in an Arden Special Landscape area.' },
  { id: 'np-be1', topic: 'design', doc: 'np', page: 29, para: 'Policy BE1', text: 'All development proposals must demonstrate how the Village Design Statement (VDS), presented in Appendix 1, has been taken into account in the design.' },
  { id: 'np-fringe', topic: 'design', doc: 'np', page: 36, para: 'Village Design Statement, settlement pattern', text: 'the fringes of Claverdon Parish consist of scattered housing such as Kington Lane, Gannaway, around Lye Green, etc.' },
  { id: 'np-density', topic: 'design', doc: 'np', page: 36, para: 'Village Design Statement, settlement guidelines', text: 'higher density development on the edges of the village should be avoided' },
  { id: 'np-lighting', topic: 'design', doc: 'np', page: 40, para: 'Village Design Statement, highways and streetscape guidelines', text: 'Discourage street lighting' },
  { id: 'np-hillfort', topic: 'design', doc: 'np', page: 35, para: 'Village Design Statement', text: 'the remains of the defensive earth works of a small Iron Age hill fort survive' },

  // ---------- development plan and employment land ----------
  { id: 'np-h3', topic: 'plan', doc: 'np', page: 12, para: 'Policy H3', text: 'The use would not conflict with any of the purposes of including land within the Green Belt or represent inappropriate development within the Green Belt' },
  { id: 'np-h3-head', topic: 'plan', doc: 'np', page: 12, para: 'Policy H3', text: 'The redevelopment of brownfield land to create new housing will be supported subject to the following criteria' },
  { id: 'np-e1', topic: 'plan', doc: 'np', page: 14, para: 'Policy E1', text: 'Development of the site for other appropriate uses will facilitate the relocation of an existing business to a more suitable site' },
  { id: 'pc-h1', topic: 'plan', doc: 'pc', page: 1, para: '1.1', text: 'Outside the Village Boundary policy is now inconsistent with NPPF, Policy GB7 and should now be given Very Limited planning weight.' },
  { id: 'pc-e1', topic: 'plan', doc: 'pc', page: 2, para: '1.4', text: 'CPC considers that, on balance, this proposed development does not comply with NDP Policy E1 nor Core Strategy CS.22' },
  { id: 'ps-relocate', topic: 'plan', doc: 'ps', page: 4, para: '2.6', text: 'The Greenfingers business is actively looking for an opportunity to re-locate the business to a larger site' },
  { id: 'ps-jobs', topic: 'plan', doc: 'ps', page: 25, para: '8.4', text: 'the business employs six full-time and one part-time members of staff' },
  { id: 'ps-open-offers', topic: 'plan', doc: 'ps', page: 27, para: '8.13', text: 'with the vendor being open to all offers being considered' },
  { id: 'mkt-terms', topic: 'plan', doc: 'mkt', page: 3, para: '4.1', text: 'it was agreed to make clear to interested parties that the ongoing business was not for sale and that offers to redevelop the site for residential purposes would not be accepted' },
  { id: 'mkt-business', topic: 'plan', doc: 'mkt', page: 10, para: 'Appendix B, enquiry log', text: 'Wanted to buy the Business' },
  { id: 'ps-mix', topic: 'plan', doc: 'ps', page: 33, para: '9.8', text: 'it is acknowledged that these proposals do not entirely meet with this mix' },

  // ---------- the Framework ----------
  { id: 'nppf-s55', topic: 'framework', doc: 'nppf', para: 'S5(5)', text: 'This policy does not apply to development proposals in the Green Belt or on land designated as Local Green Space' },
  { id: 'nppf-s55-balance', topic: 'framework', doc: 'nppf', para: 'S5(5)', text: 'proposals should be approved unless the benefits of doing so would be substantially outweighed by any adverse effects' },
  { id: 'nppf-s52', topic: 'framework', doc: 'nppf', para: 'S5(2)', text: 'fail to comply with one of the national decision-making policies which state that development proposals should be refused in specific circumstances' },
  { id: 'nppf-gb61', topic: 'framework', doc: 'nppf', para: 'GB6(1)', text: 'Development in the Green Belt is inappropriate unless it falls within one of the categories in policy GB7.' },
  { id: 'nppf-gb62', topic: 'framework', doc: 'nppf', para: 'GB6(2)', text: 'is clearly outweighed by other considerations' },
  { id: 'nppf-gb7e', topic: 'framework', doc: 'nppf', para: 'GB7(1)(e)', text: 'The redevelopment of previously developed land (including a material change of use to residential or mixed-use including residential), which would not cause substantial harm to the openness of the Green Belt' },
  { id: 'nppf-gb7g-iii', topic: 'framework', doc: 'nppf', para: 'GB7(1)(g)(iii)', text: 'The development would be in a sustainable location, with particular reference to policy TR3 of this Framework' },
  { id: 'nppf-gb81', topic: 'framework', doc: 'nppf', para: 'GB8(1)', text: 'all of the following contributions (‘Golden Rules’) should be made' },
  { id: 'nppf-gb81b', topic: 'framework', doc: 'nppf', para: 'GB8(1)(b)', text: 'Necessary improvements to local or national infrastructure' },
  { id: 'nppf-gb82', topic: 'framework', doc: 'nppf', para: 'GB8(2)', text: 'substantial weight should be given to the importance of complying with the Golden Rules' },
  { id: 'nppf-ho81', topic: 'framework', doc: 'nppf', para: 'HO8(1)', text: 'This should be provided on-site unless' },
  { id: 'nppf-pdl', topic: 'framework', doc: 'nppf', para: 'Annex B, "Previously developed land"', text: 'Land which has been lawfully developed and is or was occupied by a permanent structure and any fixed surface infrastructure associated with it' },
  { id: 'nppf-pdl-excludes', topic: 'framework', doc: 'nppf', para: 'Annex B, "Previously developed land"', text: 'Previously developed land excludes: land that is or was last occupied by agricultural or forestry buildings' },
  { id: 'nppf-grey', topic: 'framework', doc: 'nppf', para: 'Annex B, "Grey belt"', text: 'does not strongly contribute to any of purposes (a), (b), or (d) in policy GB2' },
  { id: 'nppf-tr31a', topic: 'framework', doc: 'nppf', para: 'TR3(1)(a)', text: 'This means the location should limit the need to travel, particularly by private car, and offer a genuine choice of transport modes for residents and users' },
  { id: 'nppf-tr31a-made', topic: 'framework', doc: 'nppf', para: 'TR3(1)(a)', text: 'or which can be made so, taking into account planned improvements, including any provided for as part of the development itself' },
  { id: 'nppf-tr31e', topic: 'framework', doc: 'nppf', para: 'TR3(1)(e)', text: 'In rural areas, opportunities to improve walking, wheeling, cycling and public transport and enhance the connectivity of an area should be taken where they exist and can be supported by the development proposed.' },
  { id: 'nppf-tr32', topic: 'framework', doc: 'nppf', para: 'TR3(2)', text: 'should be used alongside other relevant quantitative or qualitative evidence in assessing the connectivity of particular locations proposed for development' },
  { id: 'nppf-tr64', topic: 'framework', doc: 'nppf', para: 'TR6(4)', text: 'or an unacceptable impact on highway safety' },
  { id: 'nppf-modes', topic: 'framework', doc: 'nppf', para: 'Annex B, "Sustainable transport modes"', text: 'Any efficient, safe and accessible means of transport with overall low impact on the environment, including walking, wheeling, cycling and public transport.' },
  { id: 'nppf-f72', topic: 'framework', doc: 'nppf', para: 'F7(2)', text: 'Where development is proposed in a location known to be at risk from any form of flooding, now or in the future, it should be refused unless' },
  { id: 'nppf-f72c', topic: 'framework', doc: 'nppf', para: 'F7(2)(c)', text: 'Any residual risk can be safely managed, and safe access and escape routes are included where appropriate, as part of an agreed emergency plan' },
  { id: 'nppf-f52', topic: 'framework', doc: 'nppf', para: 'F5(2)(b)(i)', text: 'No built development within the site boundary, including access or escape routes, land raising or other potentially vulnerable elements, would be located on an area that would be at risk of flooding from any source' },
  { id: 'nppf-dp33', topic: 'framework', doc: 'nppf', para: 'DP3(3)', text: 'Development proposals should be refused if, without clear justification, they conflict with paragraph 1 of this policy or relevant aspects of the principles in paragraph 2' },
  { id: 'nppf-ho71', topic: 'framework', doc: 'nppf', para: 'HO7(1)', text: 'substantial weight should be given to the benefits of providing homes' },
  { id: 'nppf-s61', topic: 'framework', doc: 'nppf', para: 'S6(1)(a)', text: 'The neighbourhood plan became part of the development plan five years or less before the date on which the decision is made' },

  // ---------- appeal decisions ----------
  { id: 'a72-existing', topic: 'appeals', doc: 'a-6011972', para: 'paragraph 7', text: 'buildings have a volume of between 6,130m3 - 7,270m3, a footprint of around 1,780m2 and heights of 2.9m up to 5.6m' },
  { id: 'a72-proposed', topic: 'appeals', doc: 'a-6011972', para: 'paragraph 8', text: 'The houses would have a volume of 6,260m3 a footprint of around 990m2 – 1,090m2 and a height of up to 8.6m.' },
  { id: 'a72-openness', topic: 'appeals', doc: 'a-6011972', para: 'paragraph 9', text: 'although the number of buildings and volume would reduce, the proposed dwellings would be taller, bulkier and more conspicuous' },
  { id: 'a72-paraphernalia', topic: 'appeals', doc: 'a-6011972', para: 'paragraph 9', text: 'The separate residential curtilages would also result in the introduction of domestic paraphernalia for multiple households as well as hardstanding for an access road and driveways which would further impact on openness.' },
  { id: 'a72-substantial', topic: 'appeals', doc: 'a-6011972', para: 'paragraph 9', text: 'there would be harm to spatial and visual openness and taken together the harm would be substantial' },
  { id: 'a72-lane', topic: 'appeals', doc: 'a-6011972', para: 'paragraph 12', text: 'a narrow rural road with no lighting or pavements' },
  { id: 'a72-trips', topic: 'appeals', doc: 'a-6011972', para: 'paragraph 14', text: 'The appellant states that there would be a reduction in the number of vehicle movements to and from the site. Nevertheless, the new occupants would not be in a location that would limit the need to travel, particularly by private car, or offer a genuine choice of transport modes for residents and users.' },
  { id: 'a72-existing-situation', topic: 'appeals', doc: 'a-6011972', para: 'paragraph 14', text: 'even taking into account the existing situation, this would not promote sustainable transport modes or be a sustainable location for the proposed residential development' },
  { id: 'a72-benefits', topic: 'appeals', doc: 'a-6011972', para: 'paragraph 16', text: 'Overall, the benefits would be moderate in this case.' },
  { id: 'a30-whole', topic: 'appeals', doc: 'a-6011330', para: 'paragraph 9', text: 'It is logical to require that all of the appeal site must be PDL to qualify for the exception set out under Policy GB7e of the Framework, and that requirement is not met.' },
  { id: 'a37-highway-authority', topic: 'appeals', doc: 'a-6006637', para: 'paragraph 44', text: 'necessary local highway infrastructure improvements have not been suitably identified, substantiated, or secured. This conclusion aligns with the position of the Highway Authority, which considers the mitigation measures proposed by the appellant to be inadequate.' },
  { id: 'a37-willing', topic: 'appeals', doc: 'a-6006637', para: 'paragraph 44', text: 'notwithstanding the appellant’s willingness to fund certain improvements, it has not been satisfactorily demonstrated that necessary improvements to local infrastructure would be delivered' },
  { id: 'a29-depth', topic: 'appeals', doc: 'a-6010729', para: 'paragraph 17', text: 'the access route could flood to a maximum of 0.68m' },
  { id: 'a29-plan', topic: 'appeals', doc: 'a-6010729', para: 'paragraph 19', text: 'in the absence of a robust formal emergency plan, I cannot be sure that future occupants would be safe during a flood event' },
  { id: 'a13-neutral', topic: 'appeals', doc: 'a-6010313', para: 'paragraph 36', text: 'the absence of harm would be a neutral matter which would not carry weight in favour of the scheme' },
];
